sidebar:
  menu:
    post: '[博客](/)'
    wiki: '[文档](/wiki/)'
    notes: '[便笺](/notes/)'
    more: '[关于](/about/)'
  # Sidebar widgets
  widgets:
    default_layout: [welcome, recent]
    # Recent update
    recent:
      layout: recent
      rss: /atom.xml # npm i hexo-generator-feed
      limit: 5 # Count of posts
    # TOC (valid only in layout:post/wiki)
    toc:
      layout: toc
      list_number: false
      min_depth: 2
      max_depth: 5
    # welcome
    welcome:
      layout: markdown
      title: 欢迎，欢迎！
      content:
        - 欢迎光临端小强的博客，本站主要用来记录日常工作学习的经验和感悟，欢迎留言交流。

comments:
  service: utterances # utterances
  utterances:
    repo: strongduanmu/blog

article:
  auto_excerpt: 200
  # npm i hexo-related-popular-posts
  related_posts:
    enable: true
    title: 您可能感兴趣的文章
    max_count: 5

footer:
  social:
    - icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/08a41b181ce68.svg"/>'
      url: https://github.com/strongduanmu
    - icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/3845874.svg"/>'
      url: https://open.spotify.com/user/strongduanmu
    - icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/3616429.svg"/>'
      url: https://unsplash.com/@strongduanmu
    - icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/942ebbf1a4b91.svg"/>'
      url: /about/#comments
  sitemap:
    '博客':
      - '[近期](/)'
      - '[分类](/categories)'
      - '[标签](/tags)'
      - '[归档](/archives)'
    '文档':
      - '[Calcite](/wiki/calcite/background.html)'
      - '[JDBC](/wiki/jdbc/preface.html)'
    '社交':
      - '[Twitter](https://twitter.com/strongduanmu)'
      - '[GitHub](https://github.com/strongduanmu)'
      - '[留言板](/about/#comments)'
    '更多':
      - '[便签](/notes)'
      - '[关于](/about)'