open_graph:
  enable: true
  twitter_id: strongduanmu

sidebar:
  menu:
    post: '[博客](/)'
    wiki: '[文档](/wiki/)'
    notes: '[便笺](/notes/)'
    more: '[关于](/about/)'
  # Sidebar widgets
  widgets:
    #### 自动生成的页面 ####
    # 主页
    home: search_blog, welcome, recent, timeline # for home
    # 博客索引页
    blog_index: search_blog, recent, timeline # for categories/tags/archives
    # 文档索引页
    wiki_index: search_docs, recent, timeline # for wiki
    # 其它（404）
    others: search, welcome, recent, timeline # for 404 and ...
    #### 手动创建的页面 ####
    # 文章内页
    post: toc, ghrepo, search_blog, ghissues # for pages using 'layout:post'
    # 文档内页
    wiki: search, ghrepo, toc, ghissues, related # for pages using 'layout:wiki'
    # 其它 layout:page 的页面
    page: welcome, toc, search # for custom pages using 'layout:page'

comments:
  service: giscus
  # giscus
  # https://giscus.app/zh-CN
  giscus:
    data-repo: strongduanmu/blog
    data-repo-id: MDEwOlJlcG9zaXRvcnkzNzQwMDk3Njg=
    data-category: Announcements
    data-category-id: DIC_kwDOFkrvqM4CZIsa
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top # top, bottom
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous

article:
  auto_excerpt: 200
  # npm i hexo-related-popular-posts
  related_posts:
    enable: true
    title: 您可能感兴趣的文章
    max_count: 5

# 文章搜索
search:
  service: local_search # local_search, todo...
  local_search: # 在 front-matter 中设置 indexing:false 来避免被搜索索引
    field: all # post, page, all
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
    codeblock: true # 是否搜索代码块（需要content: true)

######## Tag Plugins ########
tag_plugins:
  # {% image %}
  image:
    fancybox: true

mermaid:
  enable: true
  # js: https://unpkg.com/mermaid@9.0.0/dist/mermaid.min.js
  js: https://cdn.jsdelivr.net/npm/mermaid@v9/dist/mermaid.min.js
  # Available themes: default | dark | forest | neutral
  # 推荐使用 dark 主题 在夜间模式下显示效果更好
  theme: default

footer:
  social:
    - icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/08a41b181ce68.svg"/>'
      url: https://github.com/strongduanmu
    - icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/3845874.svg"/>'
      url: https://open.spotify.com/user/strongduanmu
    - icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/3616429.svg"/>'
      url: https://unsplash.com/@strongduanmu
    - icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/942ebbf1a4b91.svg"/>'
      url: /about/#comments
  sitemap:
    '博客':
      - '[近期](/)'
      - '[分类](/categories)'
      - '[标签](/tags)'
      - '[归档](/archives)'
    '文档':
      - '[Calcite](/wiki/calcite/background.html)'
      - '[JDBC](/wiki/jdbc/preface.html)'
    '社交':
      - '[Twitter](https://twitter.com/strongduanmu)'
      - '[GitHub](https://github.com/strongduanmu)'
      - '[留言板](/about/#comments)'
    '更多':
      - '[便签](/notes)'
      - '[关于](/about)'
  content: | # 支持 Markdown 格式
    本站由 [@strongduanmu](https://github.com/strongduanmu) 使用 [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) 主题创建。
    本博客所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。
